name: test con Docker

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de codigo
      - uses: actions/checkout@v5

      - name: iniciar app
      - uses: actions/setup-java@v5

      - name: Configurar Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Construir y correr el contenedor de Docker para los tests
      - uses: docker/build-push-action@v4

        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true